id: IBA701913
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T15:06:53.588980'
last_modified: '2022-05-27T15:06:53.588990'
parser: null
source_metadata:
  title: Khaḍgaviṣāṇasūtra
  language: pi
  base:
    f265F:
      title: Complete text
      base_file: f265F.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
